log4r_config:
  # define all loggers:
  loggers:
    - name          : Mercari
      level         : DEBUG
      trace         : 'true'
      outputters    : 
      - mercari_log_file
#      - console
 
  # define all outputters (incl. formatters)
  outputters:
  - type: DateFileOutputter
    name: mercari_log_file
    filename: 'test-output.log'
    dirname: 'logs'
    date_pattern: '%Y-%m-%d'
    trunc: false
    formatter:
      date_pattern: '%Y %m %d %H:%M:%S.%L %z'
      pattern     : '[%d][PID=%p,%l]-%C: %m '
      type        : PatternFormatter

  - type: StdoutOutputter
    name: console
    formatter:
      date_pattern: '%Y %m %d %H:%M:%S.%L %z'
      pattern     : '[%d-(%p)-%l]-%C: %m '
      type        : PatternFormatter
